[[plugins]]
    repo = 'fatih/vim-go'
    on_ft = ['go']

[[plugins]]
    repo = 'othree/html5.vim'
    on_ft = ['html']

[[plugins]]
    repo = 'hail2u/vim-css3-syntax'
    on_ft = ['css']

[[plugins]]
    repo = 'jelera/vim-javascript-syntax'
    on_ft = ['js']

[[plugins]]
    repo = 'tpope/vim-rails'
    on_ft = ['rb']

[[plugins]]
    repo = 'cespare/vim-toml'
    on_ft = ['toml']
