# python
[[plugins]]
    repo = 'davidhalter/jedi-vim'
    on_ft = ['python']

[[plugins]]
    repo = 'hdima/python-syntax'
    on_ft = ['python']

# Go
[[plugins]]
    repo = 'benmills/vim-golang-alternate'
    on_ft = ['go']

[[plugins]]
    repo = 'fatih/vim-go'
    on_ft = ['go']

[[plugins]]
    repo = 'vim-jp/vim-go-extra'
    on_ft = ['go']

# js
[[plugins]]
    repo = 'jelera/vim-javascript-syntax'
    on_ft = ['js']

# html
[[plugins]]
    repo = 'othree/html5.vim'
    on_ft = ['html']

# css
[[plugins]]
    repo = 'hail2u/vim-css3-syntax'
    on_ft = ['css']

# ruby
[[plugins]]
    repo = 'tpope/vim-rails'
    on_ft = ['rb']

# toml
[[plugins]]
    repo = 'cespare/vim-toml'
    on_ft = ['toml']

# markdown
[[plugins]]
    repo = 'plasticboy/vim-markdown'
    on_ft = ['markdown', 'mkd']

[[plugins]]
    repo = 'kannokanno/previm'
    on_ft = ['markdown', 'mkd']

[[plugins]]
    repo = 'tyru/open-browser.vim'
    on_ft = ['markdown', 'mkd']

