# Go
[[plugins]]
repo =  'mattn/vim-goimports'

[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = 'go'

#json
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

repo = 'rhysd/vim-fixjson'
on_ft = 'json'

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'md']

#uml
[[plugins]]
repo = 'scrooloose/vim-slumlord'
on_ft = ['pu','uml']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['pu','uml']

#Dockerfile
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'Dockerfile'

# terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf','terraform']
hook_add = '''
let g:terraform_fmt_on_save=1
'''

# flutter 
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = 'dart'
