[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo =  'prabirshrestha/async.vim'

[[plugins]]
repo =  'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo =  'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo =  'prabirshrestha/vim-lsp'

[[plugins]]
repo =  'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_source = '''
if !exists('g:tcomment_types')
	let g:tcomment_types = {}
endif
let g:tcomment_types['toml'] = '# %s'
'''


