# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
if = 'has("lua")'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ['python']

# Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# js
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

# html
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# css
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

# ruby, rails
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['rb']

[[plugins]]
repo = 'basyura/unite-rails'
on_ft = ['rb']

#json
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

repo = 'rhysd/vim-fixjson'
on_ft = ['json']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'md']

# matlab
[[plugins]]
repo = 'lazywei/vim-matlab'
on_ft = ['matlab', 'm']

#tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
